# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\"-\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"-\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"<\n\x0bOutputChunk\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\t\x12\x0f\n\x07seq_num\x18\x03 \x01(\x05\"\x1f\n\rCancelRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"!\n\x0e\x43\x61ncelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\")\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"C\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\rStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"0\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t2\xa8\x02\n\rWorkerService\x12&\n\tAssignJob\x12\x0b.JobRequest\x1a\x0c.JobResponse\x12.\n\x0fStreamJobOutput\x12\x0b.JobRequest\x1a\x0c.OutputChunk0\x01\x12,\n\tCancelJob\x12\x0e.CancelRequest\x1a\x0f.CancelResponse\x12\x32\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\x12/\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12,\n\tGetStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBREQUEST']._serialized_start=19
  _globals['_JOBREQUEST']._serialized_end=64
  _globals['_JOBRESPONSE']._serialized_start=66
  _globals['_JOBRESPONSE']._serialized_end=111
  _globals['_OUTPUTCHUNK']._serialized_start=113
  _globals['_OUTPUTCHUNK']._serialized_end=173
  _globals['_CANCELREQUEST']._serialized_start=175
  _globals['_CANCELREQUEST']._serialized_end=206
  _globals['_CANCELRESPONSE']._serialized_start=208
  _globals['_CANCELRESPONSE']._serialized_end=241
  _globals['_HEARTBEATREQUEST']._serialized_start=243
  _globals['_HEARTBEATREQUEST']._serialized_end=296
  _globals['_HEARTBEATRESPONSE']._serialized_start=298
  _globals['_HEARTBEATRESPONSE']._serialized_end=339
  _globals['_REGISTERREQUEST']._serialized_start=341
  _globals['_REGISTERREQUEST']._serialized_end=408
  _globals['_REGISTERRESPONSE']._serialized_start=410
  _globals['_REGISTERRESPONSE']._serialized_end=445
  _globals['_STATUSREQUEST']._serialized_start=447
  _globals['_STATUSREQUEST']._serialized_end=478
  _globals['_STATUSRESPONSE']._serialized_start=480
  _globals['_STATUSRESPONSE']._serialized_end=528
  _globals['_WORKERSERVICE']._serialized_start=531
  _globals['_WORKERSERVICE']._serialized_end=827
# @@protoc_insertion_point(module_scope)
